/*
 * Autogenerated file
 *
 * SPDX-License-Identifier: Apache 2.0
 */

#include "in6xxe-mux.h"

#define UART0_RTS_GPIO_0_0 IN6XXE_PINMUX(0, 0, 1, 0, 1)
#define UART0_CTS_GPIO_0_1 IN6XXE_PINMUX(0, 1, 1, 1, 0)

#define UART0_TX_GPIO_0_2 IN6XXE_PINMUX(0, 2, 1, 1, 0)
#define UART0_RX_GPIO_1_0 IN6XXE_PINMUX(1, 0, 1, 0, 1)

#define UART1_TX_GPIO_2_1 IN6XXE_PINMUX(2, 1, 1, 1, 0)
#define UART1_RX_GPIO_2_7 IN6XXE_PINMUX(2, 7, 1, 0, 1)

